### PR TITLE
Add theme support

### PR DESCRIPTION
**Pull request by MuhammadTanveer94**
# Story Title

[This is the Issue Title](https://github.com/IEEE-VIT/hangman-react/issues/1)

## Changes made

- Made this
- Did that

## How does the solution address the problem

This PR will...

## Linked issues

Resolves #1

### CODE REVIEW

**Comment by aneeshpanda** [comment]
Hi @MuhammadTanveer94, please rebase it, otherwise LGTM!

**Comment by MuhammadTanveer94** [comment]
> Hi @MuhammadTanveer94, please rebase it, otherwise LGTM!

could you please explain?. i did not get what you want.

**Comment by MuhammadTanveer94** [comment]
> Hi @MuhammadTanveer94, please rebase it, otherwise LGTM!

asking for resolved conflict?

**Comment by aneeshpanda** [comment]
> > Hi @MuhammadTanveer94, please rebase it, otherwise LGTM!
> 
> asking for resolved conflict?

Yeah!

**Pull request merged**
